### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [Elagoht/Elagoht.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by Elagoht** [comment]
Thanks for your interest. I'll add a license and a safe (iconless) theme
for terminals without Nerd font support. I'm going to do in a few hours.

**Comment by unixorn** [comment]
Cool, either comment here or file a PR against the list when you're done.

**Comment by Elagoht** [comment]
That was already done when you commented here. You can add to list.
